version: 2
updates:
  - package-ecosystem: mix
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
    open-pull-requests-limit: 10
    versioning-strategy: lockfile-only
  - package-ecosystem: npm
    directory: "/apps/concierge_site/assets"
    schedule:
      interval: daily
      time: "09:00"
    open-pull-requests-limit: 10
    versioning-strategy: lockfile-only
