unstable_features = true
struct_field_align_threshold = 30
hard_tabs = true
max_width = 80
imports_granularity = 'Crate'
group_imports = 'StdExternalCrate'
format_strings = true
wrap_comments = true
blank_lines_lower_bound = 0
blank_lines_upper_bound = 2
